name: publish
on: [push]
jobs:
  publish-hello-docker-image:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - name: login to github container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: |
      docker build . --tag ghcr.io/deselikem/hello-docker-gcr-demo:latest
      docker run ghcr.io/deselikem/hello-docker-gcr-demo:latest
      docker push ghcr.io/deselikem/hello-docker-gcr-demo:latest